theme = "glitch"

# --- Editor Settings ---
[editor]
line-number = "absolute" # Show relative line numbers (e.g., 1, 2, 3... and then -1, -2, -3 for lines above/below cursor)
auto-pairs = false        # Automatically close brackets, quotes (e.g., typing '(' inserts '()')
completion-trigger-len = 8 # Start showing completions after 1 character is typed
continue-comments = true
auto-completion = false
auto-format = true
auto-info = false

# Optional: Uncomment these lines if you want these features
# cursorline = true      # Highlight the current line
# auto-save = true       # Automatically save files after changes

[editor.cursor-shape]
insert = "bar"     # Cursor shape in insert mode
normal = "bar"   # Cursor shape in normal mode
select = "underline" # Cursor shape in select mode

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[editor.smart-tab]
enable = false
